version: '3.7'

services:
  mongo-master:
    container_name: database
    image: mongo:latest
    restart: always    
    environment:
      MONGO_INITDB_ROOT_USERNAME: vsadmin
      # Add docker secrets for password
      MONGO_INITDB_ROOT_PASSWORD: votingsystem
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db

  # Public access
  voting-api:
    container_name: voting-api
    # environment:
    #   JWT_PUBLIC_KEY: /run/secrets/voting_api_ec_public
    #   JWT_PRIVATE_KEY: /run/secrets/voting_api_ec_private
    build: 
      context: ./voting-api
      dockerfile: voting-api.Dockerfile
    restart: always
    ports:
      - 80:8080
    links:
      - mongo-master

  election-web:
    container_name: election-web
    build:
      context: ./election-web
      dockerfile: election-web.Dockerfile
    restart: always
    ports:
      - 4200:4200

  # DEV TESTING purposes only - REMOVE
  mongodb-dev:
    container_name: dev-mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-master
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: vsadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: votingsystem
    ports:
      - 8081:8081  
    links:
      - mongo-master

# secrets:
#   voting_api_ec_public:
#     file: ./ec_public.pem
#   voting_api_ec_private:
#     file: ./ec_private.pem

volumes:
  dbdata:
    