version: '3.7'

services:
  mongo-master:
    container_name: database
    image: mongo:latest
    restart: always    
    environment:
      MONGO_INITDB_ROOT_USERNAME: vsadmin
      MONGO_INITDB_ROOT_PASSWORD: votingsystem
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      # TODO - convert to an mongo-init.sh or js inside it's own dockerfile
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db

  # Public access
  voting-api:
    container_name: voting-api
    build: 
      context: ./voting-api
      dockerfile: voting-api.Dockerfile
    restart: always
    ports:
      - 80:8080
    links:
      - mongo-master

volumes:
  dbdata:
    