version: '3.7'

services:
  db:
    container_name: voting-mongodb
    image: mongo:latest
    restart: always    
    environment:
      # Add docker secrets for admin/password
      MONGO_INITDB_ROOT_USERNAME: vsadmin
      MONGO_INITDB_ROOT_PASSWORD: votingsystem
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-volume:/data/db

  # Public access
  api:
    container_name: voting-node
    build: 
      context: ./api
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - 80:8080
    links:
      - db

  # DEV TESTING purposes only - REMOVE
  db-admin-dev:
    container_name: dev-mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: voting-mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: vsadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: votingsystem
    ports:
      - 8081:8081  
    links:
      - db

volumes:
  mongo-volume:
    