apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: voting-api
  name: voting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: voting-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: voting-api
    spec:
      containers:
        - image: voting-api
          name: voting-api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
